apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-pressure
  labels:
    app: source-pressure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-pressure
  template:
    metadata:
      labels:
        app: source-pressure
    spec:
      containers:
        - name: source-pressure
          image: denis256/source-pressure:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
      hostAliases:
        - ip: "10.10.10.119"
          hostnames:
            - "kafka"
      volumes:
        - name: config
          configMap:
            name: source-pressure-config
            items:
              - key: "application.yaml"
                path: "application.yaml"