apiVersion: v1
kind: Service
metadata:
  name: access-metrics-service
  labels:
    app: access-metrics
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30123
      protocol: TCP
  selector:
    app: access-metrics